server:
  port: 8081
spring:
  webflux:
    base-path: /api/
  application:
    name: "user-service"
  devtools:
    add-properties: false
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/pg_user"
    username: "root"
    password: "1994"

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  swagger-ui:
    path: /swagger.html
    enabled: true
  api-docs:
    enabled: true
    path: /docs
  webflux:
    router:
      enabled: true

